"""initial

Revision ID: 098bf38aa411
Revises: 
Create Date: 2026-06-10 21:38:55.482701

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '098bf38aa411'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('owner_contact', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_workshop_id'), 'users', ['workshop_id'], unique=False)
    op.create_table('job_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_mechanic_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labour_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parts_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_mechanic_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_job_cards_customer_phone'), 'job_cards', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_job_cards_status'), 'job_cards', ['status'], unique=False)
    op.create_index(op.f('ix_job_cards_vehicle_number'), 'job_cards', ['vehicle_number'], unique=False)
    op.create_index(op.f('ix_job_cards_workshop_id'), 'job_cards', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_cards_workshop_id'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_vehicle_number'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_status'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_customer_phone'), table_name='job_cards')
    op.drop_table('job_cards')
    op.drop_index(op.f('ix_users_workshop_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_table('users')
    op.drop_table('workshops')
    # ### end Alembic commands ###
